application:
  animal:
    name: Barsik, Layka, Baron, Druzhok, Vasya, Nemo
    type: Fox, Bear, Fish, Cat
    breed: Rare, Common, Uncommon, Extinct
  habitat:
    area: Sea, Forest, Desert, Jungle
  provider:
    name: Zoo, Zavr, Petty Store, Best Pets
    phone: 952-954-24-54, 924-452-65-62, 976-256-11-36, 945-591-05-81
  path: "demo-application/src/main/resources/animals/logData.txt"
  results: "demo-application/src/main/resources/results"

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5555/mts_fintech'
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: animals
    user: admin
    password: admin
    url: 'jdbc:postgresql://localhost:5555/mts_fintech'
    baseline-on-migrate: true

